/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apkpbo;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.JTableHeader;
import javax.swing.table.DefaultTableCellRenderer;


/**
 *
 * @author Nanda Prihadi
 */
public class forminputgajipns extends javax.swing.JFrame {
    private String imagePath;
    private String selectedFileName;
    private Timer timer;
    private int x;
    /**
     * Creates new form datakaryawan
     */
    private static final String DB_URL = "jdbc:mysql://localhost:3306/aplikasi_database";
    private static final String DB_USER = "root";
    private static final String DB_PASS = "";

   
    public forminputgajipns(String nama) {
        initComponents();
        namaField.setText(nama);
    x = jPanel4.getWidth();

        timer = new Timer(15, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                x--;
                if (x + marqueeLabel.getWidth() < 0) {
                    x = jPanel1.getWidth();
                }
                marqueeLabel.setLocation(x, marqueeLabel.getY());
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        marqueeLabel = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        nameValue = new javax.swing.JLabel();
        passValue = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        emailValue = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        inputgajiButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        bulanField = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        tahunField = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        golonganCombo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        fungsionalCombo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        masakerjaSpin = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        keterlambatanCombo = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        potonganField = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        frekuensiCombo = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        gajipokokField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jabatanfield = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        kenaikanMasaKerjaField = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        kinerjaField = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        keluargaField = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        transportasiField = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        totalField = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        roundedPanel1 = new apkpbo.RoundedPanel();
        roundedPanel2 = new apkpbo.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Management - Input Gaji");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel4.setBackground(new java.awt.Color(0, 51, 153));

        marqueeLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        marqueeLabel.setForeground(new java.awt.Color(255, 255, 255));
        marqueeLabel.setText("Warning! Anda sedang masuk di halaman admin. Gunakanlah dengan bijak.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(marqueeLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(marqueeLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        main.setBackground(new java.awt.Color(255, 255, 255));

        nameValue.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        nameValue.setText("nama");
        nameValue.setVisible(false);

        passValue.setText("pass");
        passValue.setVisible(false);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setText("Input Gaji Pegawai");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Setelah mengisi form Input Gaji, Jangan lupa untuk menekan tombol input gaji.");

        emailValue.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        emailValue.setText("email");
        emailValue.setVisible(false);

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));

        inputgajiButton.setBackground(new java.awt.Color(0, 102, 204));
        inputgajiButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        inputgajiButton.setForeground(new java.awt.Color(255, 255, 255));
        inputgajiButton.setText("Input Gaji");
        inputgajiButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        inputgajiButton.setContentAreaFilled(false);
        inputgajiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputgajiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputgajiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(inputgajiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel18.setText("Nama");

        namaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaFieldActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel20.setText("Bulan terima gaji");

        bulanField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel21.setText("Tahun");

        tahunField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tahunField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunFieldActionPerformed(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(0, 102, 204));

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Data Penerima Gaji");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        golonganCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Golongan PNS", "Golongan I/a", "Golongan I/b", "Golongan I/c", "Golongan I/d", "Golongan II/a", "Golongan II/b", "Golongan II/c", "Golongan II/d", "Golongan III/a", "Golongan III/b", "Golongan III/c", "Golongan III/d", "Golongan IV/a", "Golongan IV/b", "Golongan IV/c", "Golongan IV/d", "Golongan IV/e" }));
        golonganCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                golonganComboActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel12.setText("Golongan PNS");

        fungsionalCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jabatan Fungsional", "Guru Utama", "Guru Madya", "Guru Muda", "Guru Pertama", "Guru Penyelia" }));
        fungsionalCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fungsionalComboItemStateChanged(evt);
            }
        });
        fungsionalCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fungsionalComboActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel13.setText("Jabatan Fungsional");

        masakerjaSpin.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 2));
        masakerjaSpin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                masakerjaSpinStateChanged(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel17.setText("Tahun");

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel16.setText("Masa Kerja*");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(masakerjaSpin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17))
                            .addComponent(fungsionalCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 186, Short.MAX_VALUE)
                            .addComponent(golonganCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tahunField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bulanField, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bulanField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tahunField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(golonganCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fungsionalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masakerjaSpin)
                    .addComponent(jLabel17))
                .addGap(20, 20, 20))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel25.setText("Keterlambatan");

        keterlambatanCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak pernah", "1-30 menit", "31-60 menit", ">60 menit" }));
        keterlambatanCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                keterlambatanComboItemStateChanged(evt);
            }
        });
        keterlambatanCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keterlambatanComboActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel43.setText("Total Potongan");

        potonganField.setText("0");
        potonganField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                potonganFieldFocusLost(evt);
            }
        });
        potonganField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potonganFieldActionPerformed(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel44.setText("Rp.");

        frekuensiCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak pernah", "1 kali", "2 kali", ">2 kali" }));
        frekuensiCombo.setPreferredSize(new java.awt.Dimension(186, 22));
        frekuensiCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                frekuensiComboItemStateChanged(evt);
            }
        });
        frekuensiCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frekuensiComboActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel34.setText("Frekuensi dalam sebulan");

        jPanel13.setBackground(new java.awt.Color(0, 102, 204));

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Potongan");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25)
                    .addComponent(jLabel43)
                    .addComponent(jLabel34)
                    .addComponent(frekuensiCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(potonganField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(keterlambatanCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keterlambatanCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frekuensiCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(potonganField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));

        jLabel27.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel27.setText("Kenaikan dari Masa Kerja");

        gajipokokField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                gajipokokFieldFocusLost(evt);
            }
        });
        gajipokokField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gajipokokFieldActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel28.setText("Gaji Pokok");

        jLabel30.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel30.setText("Tunjangan Jabatan Fungsional");

        jLabel31.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel31.setText("Rp.");

        jabatanfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jabatanfieldFocusLost(evt);
            }
        });
        jabatanfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabatanfieldActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel32.setText("Rp.");

        kenaikanMasaKerjaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                kenaikanMasaKerjaFieldFocusLost(evt);
            }
        });
        kenaikanMasaKerjaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kenaikanMasaKerjaFieldActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel33.setText("Rp.");

        jPanel11.setBackground(new java.awt.Color(0, 102, 204));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Pendapatan");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gajipokokField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel28)
                            .addComponent(jLabel30)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel32)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jabatanfield, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel33)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(kenaikanMasaKerjaField))))
                        .addContainerGap(30, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gajipokokField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jabatanfield, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kenaikanMasaKerjaField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));

        jLabel36.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel36.setText("Tunjangan Transportasi");

        kinerjaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                kinerjaFieldFocusLost(evt);
            }
        });
        kinerjaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kinerjaFieldActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel37.setText("Tunjangan Kinerja");

        jLabel39.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel39.setText("Tunjangan Keluarga");

        jLabel40.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel40.setText("Rp.");

        keluargaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                keluargaFieldFocusLost(evt);
            }
        });
        keluargaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluargaFieldActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel41.setText("Rp.");

        transportasiField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                transportasiFieldFocusLost(evt);
            }
        });
        transportasiField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transportasiFieldActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel42.setText("Rp.");

        jPanel12.setBackground(new java.awt.Color(0, 102, 204));

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Tunjangan");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(keluargaField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel39)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transportasiField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kinerjaField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel37))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kinerjaField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keluargaField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transportasiField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel14.setBackground(new java.awt.Color(51, 102, 255));

        jPanel15.setBackground(new java.awt.Color(0, 102, 204));

        jLabel26.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Total Pendapatan");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        totalField.setBackground(new java.awt.Color(51, 102, 255));
        totalField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalField.setForeground(new java.awt.Color(255, 255, 255));
        totalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalFieldActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Rp.");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45))
                .addContainerGap())
        );

        back.setBackground(new java.awt.Color(0, 102, 204));
        back.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        back.setForeground(new java.awt.Color(0, 102, 204));
        back.setText("Back");
        back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel22.setText("*Jika masa kerja ganjil, maka pilih angka sebelumnya.");

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(passValue)
                .addGap(18, 18, 18)
                .addComponent(nameValue)
                .addGap(18, 18, 18)
                .addComponent(emailValue)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(mainLayout.createSequentialGroup()
                            .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(mainLayout.createSequentialGroup()
                                    .addGap(204, 204, 204)
                                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel22))
                            .addGap(93, 93, 93)))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(mainLayout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainLayout.createSequentialGroup()
                                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passValue)
                            .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nameValue)
                                .addComponent(emailValue)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        roundedPanel1.setBackground(new java.awt.Color(0, 102, 204));
        roundedPanel1.setRoundBottomLeft(100);

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        roundedPanel2.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel2.setRoundTopRight(100);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1147, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void setUserDetails(String name, String Email, String password) {
        nameValue.setText(name);
        emailValue.setText(Email);
        passValue.setText(password);
    }
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        inputgaji InputGajiFrame = new inputgaji();
        InputGajiFrame.setUserDetails(nameValue.getText(), emailValue.getText(), passValue.getText());
        InputGajiFrame.setVisible(true);
        InputGajiFrame.pack();
        InputGajiFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void namaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaFieldActionPerformed

    private void tahunFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunFieldActionPerformed

    private void inputgajiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputgajiButtonActionPerformed
        String Nama, GolonganPNS, JabatanFungsional, MasaKerja, Keterlambatan, Frekuensi, Bulan;
        String Tahun, GajiPokok, TunjanganKinerja, TunjanganJabatanFungsional, TunjanganKeluarga, TunjanganTransportasi, KenaikanMasaKerja, TotalPotongan, TotalPendapatan;

        String SUrl = "jdbc:mysql://localhost:3306/aplikasi_database";
        String SUser = "root";
        String SPass = "";

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            
            Nama = namaField.getText();
            GolonganPNS = golonganCombo.getSelectedItem().toString();
            Bulan = bulanField.getSelectedItem().toString();
            JabatanFungsional = fungsionalCombo.getSelectedItem().toString();
            MasaKerja = masakerjaSpin.getValue().toString();
            Keterlambatan = keterlambatanCombo.getSelectedItem().toString();
            Frekuensi = frekuensiCombo.getSelectedItem().toString();
            Tahun = tahunField.getText();
            GajiPokok = gajipokokField.getText();
            TunjanganKinerja = kinerjaField.getText();
            TunjanganJabatanFungsional = jabatanfield.getText();
            TunjanganKeluarga = keluargaField.getText();
            TunjanganTransportasi = transportasiField.getText();
            KenaikanMasaKerja = kenaikanMasaKerjaField.getText();
            TotalPotongan = potonganField.getText();
            TotalPendapatan = totalField.getText();
            
            String query = "INSERT INTO gaji (nama, golongan_pns, jabatan_fungsional, masa_kerja, keterlambatan, frekuensi, tahun, gaji_pokok, tunjangan_kinerja, tunjangan_jabatan_fungsional, tunjangan_keluarga, tunjangan_transportasi, kenaikan_masa_kerja, total_potongan, total_pendapatan, bulan) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = con.prepareStatement(query);

            ps.setString(1, Nama);
            ps.setString(2, GolonganPNS);
            ps.setString(3, JabatanFungsional);
            ps.setString(4, MasaKerja);
            ps.setString(5, Keterlambatan);
            ps.setString(6, Frekuensi);
            ps.setString(7, Tahun);
            ps.setString(8, GajiPokok);
            ps.setString(9, TunjanganKinerja);
            ps.setString(10, TunjanganJabatanFungsional);
            ps.setString(11, TunjanganKeluarga);
            ps.setString(12, TunjanganTransportasi);
            ps.setString(13, KenaikanMasaKerja);
            ps.setString(14, TotalPotongan);
            ps.setString(15, TotalPendapatan);
            ps.setString(16, Bulan);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data Gaji berhasil ditambahkan!");

            inputgaji InputGajiFrame = new inputgaji();
            InputGajiFrame.setUserDetails(nameValue.getText(), emailValue.getText(), passValue.getText());
            InputGajiFrame.setVisible(true);
            InputGajiFrame.pack();
            InputGajiFrame.setLocationRelativeTo(null);
            this.dispose();     
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
            JOptionPane.showMessageDialog(new JFrame(), "Error: " + e.getMessage(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_inputgajiButtonActionPerformed

    private void gajipokokFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gajipokokFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gajipokokFieldActionPerformed

    private void jabatanfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabatanfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jabatanfieldActionPerformed

    private void kenaikanMasaKerjaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kenaikanMasaKerjaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kenaikanMasaKerjaFieldActionPerformed

    private void kinerjaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kinerjaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kinerjaFieldActionPerformed

    private void keluargaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluargaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keluargaFieldActionPerformed

    private void transportasiFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportasiFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transportasiFieldActionPerformed

    private void potonganFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potonganFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potonganFieldActionPerformed

    private void golonganComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_golonganComboActionPerformed
        String golongan = (String) golonganCombo.getSelectedItem();

        // Mengatur gaji pokok berdasarkan pilihan golongan
        switch (golongan) {
            case "Golongan PNS":
            gajipokokField.setText("");
            break;
            case "Golongan I/a":
            gajipokokField.setText("1,560,000");
            break;
            case "Golongan I/b":
            gajipokokField.setText("1,602,700");
            break;
            case "Golongan I/c":
            gajipokokField.setText("1,646,100");
            break;
            case "Golongan I/d":
            gajipokokField.setText("1,688,700");
            break;
            case "Golongan II/a":
            gajipokokField.setText("2,022,200");
            break;
            case "Golongan II/b":
            gajipokokField.setText("2,208,400");
            break;
            case "Golongan II/c":
            gajipokokField.setText("2,301,800");
            break;
            case "Golongan II/d":
            gajipokokField.setText("2,399,200");
            break;
            case "Golongan III/a":
            gajipokokField.setText("2,579,400");
            break;
            case "Golongan III/b":
            gajipokokField.setText("2,688,500");
            break;
            case "Golongan III/c":
            gajipokokField.setText("2,802,300");
            break;
            case "Golongan III/d":
            gajipokokField.setText("2,920,800");
            break;
            case "Golongan IV/a":
            gajipokokField.setText("3,044,300");
            break;
            case "Golongan IV/b":
            gajipokokField.setText("3,173,900");
            break;
            case "Golongan IV/c":
            gajipokokField.setText("3,307,300");
            break;
            case "Golongan IV/d":
            gajipokokField.setText("3,444,600");
            break;
            case "Golongan IV/e":
            gajipokokField.setText("3,586,500");
            break;
            default:
            break;
        }
    }//GEN-LAST:event_golonganComboActionPerformed

    private void fungsionalComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fungsionalComboItemStateChanged
        String fungsional = (String) fungsionalCombo.getSelectedItem();

        // Mengatur gaji pokok berdasarkan pilihan golongan
        switch (fungsional) {
            case "Jabatan Fungsional":
            jabatanfield.setText("");
            break;
            case "Guru Utama":
            jabatanfield.setText("1,500,000");
            break;
            case "Guru Madya":
            jabatanfield.setText("1,200,000");
            break;
            case "Guru Muda":
            jabatanfield.setText("950,000");
            break;
            case "Guru Pertama":
            jabatanfield.setText("540,000");
            break;
            case "Guru Penyelia":
            jabatanfield.setText("490,000");
            break;

            default:
            break;
        }
    }//GEN-LAST:event_fungsionalComboItemStateChanged

    private void fungsionalComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fungsionalComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fungsionalComboActionPerformed

    private void masakerjaSpinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_masakerjaSpinStateChanged
        int masaKerja = (int) masakerjaSpin.getValue();
        String golongan = (String) golonganCombo.getSelectedItem();

        // Menentukan kenaikan masa kerja berdasarkan masa kerja dan golongan
        int kenaikanMasaKerja = 0;
        if (golongan.equals("Golongan I/a")) {
            kenaikanMasaKerja = masaKerja * 54500;
        }
        else if (golongan.equals("Golongan I/b")) {
            kenaikanMasaKerja = masaKerja * 57500;
        }
        else if (golongan.equals("Golongan I/c")) {
            kenaikanMasaKerja = masaKerja * 58500;
        }
        else if (golongan.equals("Golongan I/d")) {
            kenaikanMasaKerja = masaKerja * 61000;
        }
        else if (golongan.equals("Golongan II/a")) {
            kenaikanMasaKerja = masaKerja * 71500;
        }
        else if (golongan.equals("Golongan II/b")) {
            kenaikanMasaKerja = masaKerja * 73000;
        }
        else if (golongan.equals("Golongan II/c")) {
            kenaikanMasaKerja = masaKerja * 75000;
        }
        else if (golongan.equals("Golongan II/d")) {
            kenaikanMasaKerja = masaKerja * 76500;
        }
        else if (golongan.equals("Golongan III/a")) {
            kenaikanMasaKerja = masaKerja * 82000;
        }
        else if (golongan.equals("Golongan III/b")) {
            kenaikanMasaKerja = masaKerja * 84000;
        }
        else if (golongan.equals("Golongan III/c")) {
            kenaikanMasaKerja = masaKerja * 86750;
        }
        else if (golongan.equals("Golongan III/d")) {
            kenaikanMasaKerja = masaKerja * 88750;
        }
        else if (golongan.equals("Golongan IV/a")) {
            kenaikanMasaKerja = masaKerja * 92000;
        }
        else if (golongan.equals("Golongan IV/b")) {
            kenaikanMasaKerja = masaKerja * 94500;
        }
        else if (golongan.equals("Golongan IV/c")) {
            kenaikanMasaKerja = masaKerja * 97000;
        }
        else if (golongan.equals("Golongan IV/d")) {
            kenaikanMasaKerja = masaKerja * 99500;
        }
        else if (golongan.equals("Golongan IV/e")) {
            kenaikanMasaKerja = masaKerja * 102500;
        }

        // Mengatur nilai kenaikan masa kerja dengan format ribuan
        DecimalFormat df = new DecimalFormat("#,###");
        String formattedKenaikanMasaKerja = df.format(kenaikanMasaKerja);

        // Mengatur nilai kenaikan masa kerja
        kenaikanMasaKerjaField.setText(formattedKenaikanMasaKerja);
    }//GEN-LAST:event_masakerjaSpinStateChanged

    private void keterlambatanComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_keterlambatanComboItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_keterlambatanComboItemStateChanged

    private void keterlambatanComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keterlambatanComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keterlambatanComboActionPerformed

    private void frekuensiComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_frekuensiComboItemStateChanged
        String gajiPokokStr = gajipokokField.getText().replace(",", "");
        String keterlambatan = (String) keterlambatanCombo.getSelectedItem();
        String frekuensi = (String) frekuensiCombo.getSelectedItem();
        int gajiPokok = Integer.parseInt(gajiPokokStr);

        int potongan = 0;
        if (keterlambatan.equals("1-30 menit")) {
            if (frekuensi.equals("1 kali")) {
                potongan = (int) (0.05 * gajiPokok);
            } else if (frekuensi.equals("2 kali")) {
                potongan = (int) (0.07 * gajiPokok);
            } else if (frekuensi.equals(">2 kali")) {
                potongan = (int) (0.09 * gajiPokok);
            }
        } else if (keterlambatan.equals("31-60 menit")) {
            if (frekuensi.equals("1 kali")) {
                potongan = (int) (0.10 * gajiPokok);
            } else if (frekuensi.equals("2 kali")) {
                potongan = (int) (0.15 * gajiPokok);
            } else if (frekuensi.equals(">2 kali")) {
                potongan = (int) (0.19 * gajiPokok);
            }
        } else if (keterlambatan.equals(">60 menit")) {
            if (frekuensi.equals("1 kali")) {
                potongan = (int) (0.20 * gajiPokok);
            } else if (frekuensi.equals("2 kali")) {
                potongan = (int) (0.25 * gajiPokok);
            } else if (frekuensi.equals(">2 kali")) {
                potongan = (int) (0.29 * gajiPokok);
            }
        } else if (keterlambatan.equals("Tidak pernah")) {
            if (frekuensi.equals("1Tidak pernah")) {
                potongan = (int) (0 * gajiPokok);
            }
        }

        // Mengatur nilai potongan dengan format ribuan
        DecimalFormat df = new DecimalFormat("#,###");
        String formattedPotongan = df.format(potongan);

        // Mengatur nilai potongan di potonganField
        potonganField.setText(formattedPotongan);
    }//GEN-LAST:event_frekuensiComboItemStateChanged

    private void frekuensiComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frekuensiComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frekuensiComboActionPerformed

    private void totalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalFieldActionPerformed

    private void gajipokokFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gajipokokFieldFocusLost
hitungTotal();          // TODO add your handling code here:
    }//GEN-LAST:event_gajipokokFieldFocusLost

    private void jabatanfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jabatanfieldFocusLost
hitungTotal();          // TODO add your handling code here:
    }//GEN-LAST:event_jabatanfieldFocusLost

    private void kenaikanMasaKerjaFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kenaikanMasaKerjaFieldFocusLost
hitungTotal();          // TODO add your handling code here:
    }//GEN-LAST:event_kenaikanMasaKerjaFieldFocusLost

    private void kinerjaFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kinerjaFieldFocusLost
hitungTotal();          // TODO add your handling code here:
    }//GEN-LAST:event_kinerjaFieldFocusLost

    private void keluargaFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_keluargaFieldFocusLost
hitungTotal();          // TODO add your handling code here:
    }//GEN-LAST:event_keluargaFieldFocusLost

    private void transportasiFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_transportasiFieldFocusLost
hitungTotal();          // TODO add your handling code here:
    }//GEN-LAST:event_transportasiFieldFocusLost

    private void potonganFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_potonganFieldFocusLost
hitungTotal();          // TODO add your handling code here:
    }//GEN-LAST:event_potonganFieldFocusLost
    
   private void hitungTotal() {
    // Ambil nilai string dari setiap JTextField
    String gajiPokokStr = gajipokokField.getText().replace(",", "");
    String fungsionalStr = jabatanfield.getText().replace(",", "");
    String masaKerjaStr = kenaikanMasaKerjaField.getText().replace(",", "");
    String kinerjaStr = kinerjaField.getText().replace(",", "");
    String keluargaStr = keluargaField.getText().replace(",", "");
    String transportasiStr = transportasiField.getText().replace(",", "");
    String potonganStr = potonganField.getText().replace(",", "");
    
if (gajiPokokStr.isEmpty() || fungsionalStr.isEmpty() || masaKerjaStr.isEmpty() ||
            kinerjaStr.isEmpty() || keluargaStr.isEmpty() || transportasiStr.isEmpty()|| potonganStr.isEmpty()) {
            // Jika ada yang kosong, set totalField menjadi kosong juga
            totalField.setText("");
            return;
}
    // Konversi string ke tipe data numerik
    int gajiPokok = Integer.parseInt(gajiPokokStr);
    int fungsional = Integer.parseInt(fungsionalStr);
    int masaKerja = Integer.parseInt(masaKerjaStr);
    int kinerja = Integer.parseInt(kinerjaStr);
    int keluarga = Integer.parseInt(keluargaStr);
    int transportasi = Integer.parseInt(transportasiStr);
    int potongan = Integer.parseInt(potonganStr);

    // Hitung total
    int total = gajiPokok + fungsional + masaKerja + kinerja + keluarga + transportasi - potongan;

    // Format angka total dan setel nilai ke totalField
    DecimalFormat df = new DecimalFormat("#,###");
    String formattedTotal = df.format(total);
    totalField.setText(formattedTotal);
}
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> bulanField;
    private javax.swing.JLabel emailValue;
    private javax.swing.JComboBox<String> frekuensiCombo;
    private javax.swing.JComboBox<String> fungsionalCombo;
    private javax.swing.JTextField gajipokokField;
    private javax.swing.JComboBox<String> golonganCombo;
    private javax.swing.JButton inputgajiButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jabatanfield;
    private javax.swing.JTextField keluargaField;
    private javax.swing.JTextField kenaikanMasaKerjaField;
    private javax.swing.JComboBox<String> keterlambatanCombo;
    private javax.swing.JTextField kinerjaField;
    private javax.swing.JPanel main;
    private javax.swing.JLabel marqueeLabel;
    private javax.swing.JSpinner masakerjaSpin;
    private javax.swing.JTextField namaField;
    private javax.swing.JLabel nameValue;
    private javax.swing.JLabel passValue;
    private javax.swing.JTextField potonganField;
    private apkpbo.RoundedPanel roundedPanel1;
    private apkpbo.RoundedPanel roundedPanel2;
    private javax.swing.JTextField tahunField;
    private javax.swing.JTextField totalField;
    private javax.swing.JTextField transportasiField;
    // End of variables declaration//GEN-END:variables
}
