/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apkpbo;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.JTableHeader;
import javax.swing.table.DefaultTableCellRenderer;


/**
 *
 * @author Nanda Prihadi
 */
public class forminputulasan extends javax.swing.JFrame {
    
    private Timer timer;
    private int x;
    /**
     * Creates new form datakaryawan
     */

   
    public forminputulasan(String nama) {
        initComponents();
        namaField.setText(nama);
    x = jPanel4.getWidth();

        timer = new Timer(15, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                x--;
                if (x + marqueeLabel.getWidth() < 0) {
                    x = jPanel1.getWidth();
                }
                marqueeLabel.setLocation(x, marqueeLabel.getY());
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        marqueeLabel = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        nameValue = new javax.swing.JLabel();
        passValue = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        emailValue = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        inputgajiButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        inputgajiButton1 = new javax.swing.JButton();
        pelayanan1 = new javax.swing.JRadioButton();
        pelayanan2 = new javax.swing.JRadioButton();
        pelayanan3 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        kebersihan1 = new javax.swing.JRadioButton();
        kebersihan2 = new javax.swing.JRadioButton();
        kebersihan3 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        penampilan1 = new javax.swing.JRadioButton();
        penampilan2 = new javax.swing.JRadioButton();
        penampilan3 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desk = new javax.swing.JTextArea();
        roundedPanel1 = new apkpbo.RoundedPanel();
        roundedPanel2 = new apkpbo.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Management - Input Ulasan");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel4.setBackground(new java.awt.Color(0, 51, 153));

        marqueeLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        marqueeLabel.setForeground(new java.awt.Color(255, 255, 255));
        marqueeLabel.setText("Warning! Anda sedang masuk di halaman admin. Gunakanlah dengan bijak.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(marqueeLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(marqueeLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        main.setBackground(new java.awt.Color(255, 255, 255));

        nameValue.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        nameValue.setText("nama");
        nameValue.setVisible(false);

        passValue.setText("pass");
        passValue.setVisible(false);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setText("Beri Ulasan Karyawan");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Setelah mengisi form ulasan untuk karyawan, Jangan lupa untuk menekan tombol Kirim Ulasan");

        emailValue.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        emailValue.setText("email");
        emailValue.setVisible(false);

        namaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaFieldActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));

        inputgajiButton.setBackground(new java.awt.Color(0, 102, 204));
        inputgajiButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        inputgajiButton.setForeground(new java.awt.Color(255, 255, 255));
        inputgajiButton.setText("Beri Ulasan");
        inputgajiButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        inputgajiButton.setContentAreaFilled(false);
        inputgajiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputgajiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(inputgajiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(inputgajiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setText("Nama");

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel12.setText("Kualitas Pelayanan");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        inputgajiButton1.setBackground(new java.awt.Color(0, 102, 204));
        inputgajiButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        inputgajiButton1.setForeground(new java.awt.Color(0, 102, 204));
        inputgajiButton1.setText("Back");
        inputgajiButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        inputgajiButton1.setContentAreaFilled(false);
        inputgajiButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputgajiButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(inputgajiButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(inputgajiButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pelayanan1.setText("Sangat Memuaskan");
        pelayanan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelayanan1ActionPerformed(evt);
            }
        });

        pelayanan2.setText("Cukup Memuaskan");
        pelayanan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelayanan2ActionPerformed(evt);
            }
        });

        pelayanan3.setText("Kurang Memuaskan");

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel13.setText("Kebersihan");

        kebersihan1.setText("Sangat Bagus");
        kebersihan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kebersihan1ActionPerformed(evt);
            }
        });

        kebersihan2.setText("Cukup Bagus");
        kebersihan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kebersihan2ActionPerformed(evt);
            }
        });

        kebersihan3.setText("Kurang Bagus");

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel14.setText("Penampilan");

        penampilan1.setText("Sangat Rapi");
        penampilan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penampilan1ActionPerformed(evt);
            }
        });

        penampilan2.setText("Cukup Rapi");
        penampilan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penampilan2ActionPerformed(evt);
            }
        });

        penampilan3.setText("Kurang Rapi");

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setText("Deskripsi Singkat");

        desk.setColumns(8);
        desk.setRows(1);
        jScrollPane1.setViewportView(desk);

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(passValue)
                .addGap(18, 18, 18)
                .addComponent(nameValue)
                .addGap(18, 18, 18)
                .addComponent(emailValue)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addGroup(mainLayout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(142, Short.MAX_VALUE))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(namaField, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addGroup(mainLayout.createSequentialGroup()
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pelayanan1)
                                    .addComponent(kebersihan1)
                                    .addComponent(penampilan1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(penampilan2)
                                    .addComponent(kebersihan2)
                                    .addComponent(pelayanan2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(penampilan3)
                                    .addComponent(kebersihan3)
                                    .addComponent(pelayanan3))))
                        .addGap(123, 123, 123))))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passValue)
                    .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameValue)
                        .addComponent(emailValue)))
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(6, 6, 6)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pelayanan2)
                            .addComponent(pelayanan1)
                            .addComponent(pelayanan3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addGap(6, 6, 6)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kebersihan2)
                            .addComponent(kebersihan1)
                            .addComponent(kebersihan3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addGap(6, 6, 6)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(penampilan2)
                            .addComponent(penampilan1)
                            .addComponent(penampilan3))))
                .addGap(49, 49, 49)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        roundedPanel1.setBackground(new java.awt.Color(0, 102, 204));
        roundedPanel1.setRoundBottomLeft(100);

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        roundedPanel2.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel2.setRoundTopRight(100);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void namaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaFieldActionPerformed

    private void inputgajiButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputgajiButton1ActionPerformed
        // TODO add your handling code here:
        inputulasan InputUlasanFrame = new inputulasan();
        InputUlasanFrame.setUserDetails(nameValue.getText(), emailValue.getText(), passValue.getText());
        InputUlasanFrame.setVisible(true);
        InputUlasanFrame.pack();
        InputUlasanFrame.setLocationRelativeTo(null);
        this.dispose(); 
    }//GEN-LAST:event_inputgajiButton1ActionPerformed

    private void pelayanan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelayanan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pelayanan1ActionPerformed

    private void pelayanan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelayanan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pelayanan2ActionPerformed

    private void kebersihan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kebersihan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kebersihan1ActionPerformed

    private void kebersihan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kebersihan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kebersihan2ActionPerformed

    private void penampilan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penampilan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penampilan1ActionPerformed

    private void penampilan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penampilan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penampilan2ActionPerformed

    private void inputgajiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputgajiButtonActionPerformed
        String nama = namaField.getText();
        String deskripsi = desk.getText();
        String pelayanan = null;
        String kebersihan = null;
        String penampilan = null;
        if (pelayanan1.isSelected()) {
            pelayanan = "Sangat Memuaskan";
        } else if (pelayanan2.isSelected()) {
            pelayanan = "Cukup Memuaskan";
        } else if (pelayanan3.isSelected()) {
            pelayanan = "Kurang Memuaskan";
        }

        if (kebersihan1.isSelected()) {
            kebersihan = "Sangat Bagus";
        } else if (kebersihan2.isSelected()) {
            kebersihan = "Cukup Bagus";
        } else if (kebersihan3.isSelected()) {
            kebersihan = "Kurang Bagus";
        }

        if (penampilan1.isSelected()) {
            penampilan = "Sangat Rapi";
        } else if (penampilan2.isSelected()) {
            penampilan = "Cukup Rapi";
        } else if (penampilan3.isSelected()) {
            penampilan = "Kurang Rapi";
        }
        
            try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ulasan_karyawan", "root", "")) {
                String sql = "INSERT INTO user (nama, pelayanan, kebersihan, penampilan, deskripsi) VALUES (?, ?, ?, ?, ?)";
                PreparedStatement statement = conn.prepareStatement(sql);
                statement.setString(1, nama);
                statement.setString(2, deskripsi);
                statement.setString(3, pelayanan);
                statement.setString(4, kebersihan);
                statement.setString(5, penampilan);
                

                statement.executeUpdate();
                javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil disimpan", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                namaField.setText("");
                desk.setText("");
                
                
        
        
        inputulasan InputUlasanFrame = new inputulasan();
        InputUlasanFrame.setUserDetails(nameValue.getText(), emailValue.getText(), passValue.getText());
        InputUlasanFrame.setVisible(true);
        InputUlasanFrame.pack();
        InputUlasanFrame.setLocationRelativeTo(null);
        this.dispose();  
        
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        
        
    }//GEN-LAST:event_inputgajiButtonActionPerformed
    
   public void setUserDetails(String name, String Email, String password) {
        nameValue.setText(name);
        emailValue.setText(Email);
        passValue.setText(password);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea desk;
    private javax.swing.JLabel emailValue;
    private javax.swing.JButton inputgajiButton;
    private javax.swing.JButton inputgajiButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton kebersihan1;
    private javax.swing.JRadioButton kebersihan2;
    private javax.swing.JRadioButton kebersihan3;
    private javax.swing.JPanel main;
    private javax.swing.JLabel marqueeLabel;
    private javax.swing.JTextField namaField;
    private javax.swing.JLabel nameValue;
    private javax.swing.JLabel passValue;
    private javax.swing.JRadioButton pelayanan1;
    private javax.swing.JRadioButton pelayanan2;
    private javax.swing.JRadioButton pelayanan3;
    private javax.swing.JRadioButton penampilan1;
    private javax.swing.JRadioButton penampilan2;
    private javax.swing.JRadioButton penampilan3;
    private apkpbo.RoundedPanel roundedPanel1;
    private apkpbo.RoundedPanel roundedPanel2;
    // End of variables declaration//GEN-END:variables

  

    
}
