/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apkpbo;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.JTableHeader;
import javax.swing.table.DefaultTableCellRenderer;


/**
 *
 * @author Nanda Prihadi
 */
public class lihatulasan extends javax.swing.JFrame {

    /**
     *
     * @param name
     * @param email
     * @param telp
     * @param password
     */
   
    
    private Timer timer;
    private String nama, Email, telp, password;
    private byte[] foto;
    private int x;
    /**
     * Creates new form datakaryawan
     */

   
    public lihatulasan(String seleksinama, String seleksideskripsi, String seleksipelayanan, String seleksikebersihan, String seleksipenampilan) {
        initComponents();
        namaField.setText(seleksinama);
        desk.setText(seleksideskripsi);
        pelayanan.setText(seleksipelayanan);
        if ("Sangat Memuaskan".equalsIgnoreCase(seleksipelayanan)){
            pelayanan1.setSelected(true);
        }
        else if ("Cukup Memuaskan".equalsIgnoreCase(seleksipelayanan)){
            pelayanan2.setSelected(true);
        }
       else if ("Kurang Memuaskan".equalsIgnoreCase(seleksipelayanan)){
            pelayanan3.setSelected(true);
        }
        kebersihan.setText(seleksikebersihan);
        if ("Sangat Bagus".equalsIgnoreCase(seleksikebersihan)){
            kebersihan1.setSelected(true);
        }
        else if ("Cukup Bagus".equalsIgnoreCase(seleksikebersihan)){
            kebersihan2.setSelected(true);
        }
       else if ("Kurang Bagus".equalsIgnoreCase(seleksikebersihan)){
            kebersihan3.setSelected(true);
        }
        penampilan.setText(seleksipenampilan);
        if ("Sangat Rapi".equalsIgnoreCase(seleksipenampilan)){
            penampilan1.setSelected(true);
        }
        else if ("Cukup Rapi".equalsIgnoreCase(seleksipenampilan)){
            penampilan2.setSelected(true);
        }
       else if ("Kurang Rapi".equalsIgnoreCase(seleksipenampilan)){
            penampilan3.setSelected(true);
        }
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        inputgajiButton1 = new javax.swing.JButton();
        pelayanan1 = new javax.swing.JRadioButton();
        pelayanan2 = new javax.swing.JRadioButton();
        pelayanan3 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        kebersihan1 = new javax.swing.JRadioButton();
        kebersihan2 = new javax.swing.JRadioButton();
        kebersihan3 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        penampilan1 = new javax.swing.JRadioButton();
        penampilan2 = new javax.swing.JRadioButton();
        penampilan3 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        passValue = new javax.swing.JLabel();
        telpValue = new javax.swing.JLabel();
        emailValue = new javax.swing.JLabel();
        nameValue = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pelayanan = new javax.swing.JLabel();
        kebersihan = new javax.swing.JLabel();
        penampilan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desk = new javax.swing.JTextArea();
        roundedPanel1 = new apkpbo.RoundedPanel();
        roundedPanel2 = new apkpbo.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Management - Lihat Ulasan");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        main.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setText("Lihat Ulasan Karyawan");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Berikut adalah data lengkap ulasan yang diberikan kepada anda, teruslah perbaiki diri anda.");

        namaField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        namaField.setEnabled(false);
        namaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setText("Nama");

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel12.setText("Kualitas Pelayanan");

        jPanel5.setBackground(new java.awt.Color(0, 102, 204));

        inputgajiButton1.setBackground(new java.awt.Color(0, 102, 204));
        inputgajiButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        inputgajiButton1.setForeground(new java.awt.Color(255, 255, 255));
        inputgajiButton1.setText("Back");
        inputgajiButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        inputgajiButton1.setContentAreaFilled(false);
        inputgajiButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputgajiButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputgajiButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputgajiButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pelayanan1.setBackground(new java.awt.Color(255, 255, 255));
        pelayanan1.setText("Sangat Memuaskan");
        pelayanan1.setEnabled(false);
        pelayanan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelayanan1ActionPerformed(evt);
            }
        });

        pelayanan2.setText("Cukup Memuaskan");
        pelayanan2.setEnabled(false);
        pelayanan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelayanan2ActionPerformed(evt);
            }
        });

        pelayanan3.setText("Kurang Memuaskan");
        pelayanan3.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel13.setText("Kebersihan");

        kebersihan1.setText("Sangat Bagus");
        kebersihan1.setEnabled(false);
        kebersihan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kebersihan1ActionPerformed(evt);
            }
        });

        kebersihan2.setText("Cukup Bagus");
        kebersihan2.setEnabled(false);
        kebersihan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kebersihan2ActionPerformed(evt);
            }
        });

        kebersihan3.setText("Kurang Bagus");
        kebersihan3.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel14.setText("Penampilan");

        penampilan1.setText("Sangat Rapi");
        penampilan1.setEnabled(false);
        penampilan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penampilan1ActionPerformed(evt);
            }
        });

        penampilan2.setText("Cukup Rapi");
        penampilan2.setEnabled(false);
        penampilan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penampilan2ActionPerformed(evt);
            }
        });

        penampilan3.setText("Kurang Rapi");
        penampilan3.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setText("Deskripsi Singkat");

        jPanel6.setVisible(false);

        passValue.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        passValue.setForeground(new java.awt.Color(255, 255, 255));
        passValue.setText("User");

        telpValue.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        telpValue.setForeground(new java.awt.Color(255, 255, 255));
        telpValue.setText("Telepon");

        emailValue.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        emailValue.setForeground(new java.awt.Color(255, 255, 255));
        emailValue.setText("Email");

        nameValue.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        nameValue.setForeground(new java.awt.Color(255, 255, 255));
        nameValue.setText("User");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telpValue)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(passValue)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(emailValue)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nameValue)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(telpValue)
                .addGap(41, 41, 41))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 24, Short.MAX_VALUE)
                    .addComponent(passValue)
                    .addGap(0, 23, Short.MAX_VALUE)))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 24, Short.MAX_VALUE)
                    .addComponent(emailValue)
                    .addGap(0, 23, Short.MAX_VALUE)))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 24, Short.MAX_VALUE)
                    .addComponent(nameValue)
                    .addGap(0, 23, Short.MAX_VALUE)))
        );

        jPanel2.setVisible(false);

        pelayanan.setText("jLabel2");

        kebersihan.setText("jLabel2");

        penampilan.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pelayanan)
                    .addComponent(kebersihan)
                    .addComponent(penampilan))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pelayanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kebersihan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(penampilan)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        desk.setColumns(1);
        desk.setRows(1);
        desk.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        desk.setEnabled(false);
        desk.setName(""); // NOI18N
        jScrollPane1.setViewportView(desk);

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addGroup(mainLayout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane1)
                            .addComponent(namaField, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addGroup(mainLayout.createSequentialGroup()
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pelayanan1)
                                    .addComponent(kebersihan1)
                                    .addComponent(penampilan1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(penampilan2)
                                    .addComponent(kebersihan2)
                                    .addComponent(pelayanan2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(penampilan3)
                                    .addComponent(kebersihan3)
                                    .addComponent(pelayanan3))))
                        .addGap(123, 123, 123))))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(29, 29, 29)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(mainLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(6, 6, 6)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pelayanan2)
                                    .addComponent(pelayanan1)
                                    .addComponent(pelayanan3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addGap(6, 6, 6)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(kebersihan2)
                                    .addComponent(kebersihan1)
                                    .addComponent(kebersihan3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addGap(6, 6, 6)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(penampilan2)
                                    .addComponent(penampilan1)
                                    .addComponent(penampilan3)))
                            .addGroup(mainLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        roundedPanel1.setBackground(new java.awt.Color(0, 102, 204));
        roundedPanel1.setRoundBottomLeft(100);

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        roundedPanel2.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel2.setRoundTopRight(100);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void namaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaFieldActionPerformed

    private void inputgajiButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputgajiButton1ActionPerformed
        // TODO add your handling code here:
        ulasan HomeFrame = new ulasan();
        HomeFrame.setVisible(true);
        HomeFrame.setUserDetails(nama, Email, telp, password, foto);
        HomeFrame.pack();
        HomeFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_inputgajiButton1ActionPerformed

    private void pelayanan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelayanan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pelayanan1ActionPerformed

    private void pelayanan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelayanan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pelayanan2ActionPerformed

    private void kebersihan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kebersihan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kebersihan1ActionPerformed

    private void kebersihan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kebersihan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kebersihan2ActionPerformed

    private void penampilan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penampilan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penampilan1ActionPerformed

    private void penampilan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penampilan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penampilan2ActionPerformed
    public void setUserDetails(String name, String Email, String telp, String password, byte[] foto) {
        this.nama = name;
        this.Email = Email;
        this.telp = telp;
        this.password = password;
        this.foto = foto;
        nameValue.setText(name);
        emailValue.setText(Email);
        telpValue.setText(telp);
        passValue.setText(password);
    }
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea desk;
    private javax.swing.JLabel emailValue;
    private javax.swing.JButton inputgajiButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kebersihan;
    private javax.swing.JRadioButton kebersihan1;
    private javax.swing.JRadioButton kebersihan2;
    private javax.swing.JRadioButton kebersihan3;
    private javax.swing.JPanel main;
    private javax.swing.JTextField namaField;
    private javax.swing.JLabel nameValue;
    private javax.swing.JLabel passValue;
    private javax.swing.JLabel pelayanan;
    private javax.swing.JRadioButton pelayanan1;
    private javax.swing.JRadioButton pelayanan2;
    private javax.swing.JRadioButton pelayanan3;
    private javax.swing.JLabel penampilan;
    private javax.swing.JRadioButton penampilan1;
    private javax.swing.JRadioButton penampilan2;
    private javax.swing.JRadioButton penampilan3;
    private apkpbo.RoundedPanel roundedPanel1;
    private apkpbo.RoundedPanel roundedPanel2;
    private javax.swing.JLabel telpValue;
    // End of variables declaration//GEN-END:variables

   


    
}
